dist: xenial
language: php

php:
    - "7.2"

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - cp .env.travis .env
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - vendor/bin/phpunit
