dist: xenial
language: php

cache:
    directories:
        - $HOME/.composer/cache
        - node_modules

before_script:
    - cp .env.travis .env
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

matrix:
    include:
        - language: php
          php:
              - "7.2"
          before_script:
              - cp .env.travis .env
              - travis_retry composer self-update
              - travis_retry composer install --no-interaction
          script:
              - vendor/bin/phpunit
        - language: node_js
          node_js:
              - "node"
          before_script:
              - yarn
          script:
              - yarn test

notifications:
    email: false
